---
- name: play for cisco routers
  hosts: routers
  gather_facts: false
  tasks:
    - name: gathering facts
      ios_facts:
      register: router_info
      
    #- debug: 
    #    var: router_info 
     
    - name: router version
      ios_command:
        commands:  show version
        
    - name: router interface brief
      ios_command:
        commands: show ip interface brief
