---
- name: play for ip config
  hosts: cisco
  gather_facts: false
  tasks:
#var, conditions #roles > galaxy.ansible.com  vty 
    - name: set ip address on router's interface
      ios_config:
         lines:  #commands
           - ip  address  10.0.2.105  255.255.255.0
           - no shutdown
         parents: int g3   #sub config mode for int
         save_when: changed

    #- name: save from RAM TO NVRAM
    #  ios_command:     #privilege execution mode/enable mode   #router1#
    #    commands: write
