---
- name: play for ip config
  hosts: cisco
  gather_facts: false
  tasks:
   - name: enable OSPF protocol
     ios_config:
       lines:
         - router-id 1.1.1.1
         - network 192.168.56.105  0.0.0.255 area 0
       parents: router ospf 1   #protocl config sub interface
